# Generated by Django 4.0 on 2021-12-24 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recip_name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('curr_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('search_query', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_contributed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('keyword', models.CharField(max_length=50)),
                ('gift_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_coordinator.giftpool')),
            ],
        ),
    ]
