# Generated by Django 4.0 on 2021-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_coordinator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='giftpool',
            name='recip_name',
        ),
        migrations.AddField(
            model_name='contributor',
            name='keyword1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contributor',
            name='keyword2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contributor',
            name='keyword3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='giftpool',
            name='recipient_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='amount_contributed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='giftpool',
            name='curr_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='giftpool',
            name='search_query',
            field=models.CharField(default='', max_length=200),
        ),
    ]
