# Generated by Django 4.0 on 2021-12-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_coordinator', '0002_remove_contributor_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpool',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
